### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by Pic-Inu** [megavolt85/tools_for_DC#1]
bat gives this error:
```
Converting "Legacy to "Legiso ...
Error!
```
Can you please take a look at this ? 
Maybe the tool compatibility must be updated for windows 10 64 bits.

Thanks !

**Comment by megavolt85** [comment]
need more information
log, screenshot your folder with image

**Comment by Pic-Inu** [comment]
Sorry for the issue. The problem seemed to come from the images disc I dowloaded. I tried with the gdi optimizer from isomake pack 2.4 and everything was working.
